CREATE TABLE `table_1` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT,
  `date` DATETIME,
  `price` DECIMAL(6,2) DEFAULT 0.0000,
  `created` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `updated` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
